/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main {
   public static void main(String args[]) throws Exception {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter name of a computer: ");
       String name = in.readLine();
       System.out.print("Enter color of a computer: ");
       String Color = in.readLine();
       System.out.print("Enter series of a computer: ");
       String series = in.readLine();       
       System.out.print("Enter price of a computer: ");
       double price = Double.parseDouble(in.readLine());
       System.out.printf("1. TC = 1 - test toString function\n2. TC = 2 - test getSalePrice function"
               + "\n3. TC = 3 - test Name function\n");       
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");      
       switch (tc) {
           case 1:
               {
                   Computer m = new Computer(name, Color, price);
                   System.out.println(m);
                   m = new SComputer(series,name, Color, price);
                   System.out.println(m);
                   break;
               }
           case 2:
               SComputer b = new SComputer(series, name, Color, price);
               System.out.println(b.getSalePrice());
               break;
           case 3:
               {
                   Computer m = new Computer(name, Color, price);
                   System.out.println(m.getName());
                   break;
               }
           default:
               break;
       }
   }
 }
